lists   

In [4]:
a=[1,2,'hehe']
print(a)
print(len(a))

[1, 2, 'hehe']
3


                        Tuple
Tuple-once created it cannot be modified

In [5]:
a=(2,'hii')
print(a)

(2, 'hii')


set

In [10]:
s=set([1,3,2,'hi','hi','bye',2,0])
print(s)
for i in s:
    print(i)

{0, 1, 2, 3, 'hi', 'bye'}
0
1
2
3
hi
bye


dictionary

In [18]:
d={1:2,3:'hmm',0:[1,2,3,4,5,6],'hi':44}
print(d)
print(d[0],d['hi'])

{1: 2, 3: 'hmm', 0: [1, 2, 3, 4, 5, 6], 'hi': 44}
[1, 2, 3, 4, 5, 6] 44


matrix

In [38]:
import numpy as np 
a = np.array([[1,2,3,4],[4,55,1,2],
              [8,3,20,19]])
m = np.reshape(a,(3, 4))
print(m)
m = np.append(m,[[1, 15,13,11]],0)
print(m)
print(m[0])
m=np.delete(m,[2],0)
print(m)

[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]]
[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 8  3 20 19]
 [ 1 15 13 11]]
[1 2 3 4]
[[ 1  2  3  4]
 [ 4 55  1  2]
 [ 1 15 13 11]]


linked list